### ISSUE TITLE
arm-none-eabi-gcc 应该是什么版本

### ISSUE THREAD

**Issue by SIchenJi** [amov-lab/Prometheus#101]
ubuntu.sh里安装的gcc-arm是9-2020-q2-update，但wiki里写的是7-2017-q4-major

**Comment by Lingbo-M** [comment]
请问您解决该问题了，我也遇到这个问题，运行prometheus_px4相关功能包失败。

**Comment by potato77** [comment]
> ubuntu.sh

你说的是对的，固件能正常编译即可，一般PX4固件会支持多个版本。
