### ISSUE TITLE
gazebo缺少模型的错误用什么办法解决呢

### ISSUE THREAD

**Issue by SIchenJi** [amov-lab/Prometheus#102]
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sichenji/Prometheus/Simulator/gazebo_simulator/models/MultiUAV"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sichenji/Prometheus/Simulator/gazebo_simulator/models/race_track"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sichenji/Prometheus/Simulator/gazebo_simulator/models/texture"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sichenji/Prometheus/Simulator/gazebo_simulator/models/texture_amov"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sichenji/Prometheus/Simulator/gazebo_simulator/amov_models/MultiUAV"
INFO  [ecl/EKF] 3104000: EKF aligned, (baro hgt, IMU buf: 18, OBS buf: 14)
INFO  [ecl/EKF] 3104000: reset position to last known position
INFO  [ecl/EKF] 3104000: reset velocity to zero
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
INFO  [ecl/EKF] 5384000: reset position to GPS
INFO  [ecl/EKF] 5384000: reset velocity to GPS
INFO  [ecl/EKF] 5384000: starting GPS fusion
[Err] [ModelDatabase.cc:390] Unable to parse model.config for model[http://gazebosim.org/models/bin_4_dropping_task]

**Comment by lzh-awesome** [comment]
路径文件吧 要把阿木的模型下载到本地

**Comment by kavinwkp** [comment]
请问能说具体一点嘛 @lzh-awesome

**Comment by potato77** [comment]
这个不影响，可忽略。
