### ISSUE TITLE
error in file: Modules/control/include/state_from_mavros.h

### ISSUE THREAD

**Issue by gaia442993802** [amov-lab/Prometheus#104]
code in file: 
            _DroneState.attitude_rate[0] = msg->angular_velocity.x;
            _DroneState.attitude_rate[1] = msg->angular_velocity.x;
            _DroneState.attitude_rate[2] = msg->angular_velocity.x;

should be:
            _DroneState.attitude_rate[0] = msg->angular_velocity.x;
            _DroneState.attitude_rate[1] = msg->angular_velocity.y;
            _DroneState.attitude_rate[2] = msg->angular_velocity.z;

**Comment by 473867143** [comment]
Ths ! We will fix it later.
