### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by b369147** [amov-lab/Prometheus#106]
执行：
make amovlab_sitl_default gazebo
所出现的错误

pxh> [Err] [InsertModelWidget.cc:426] Missing model.config for model "/home/a/Prometheus/Simulator/gazebo_simulator/models/MultiUAV"
[Err] [InsertModelWidget.cc:426] Missing model.config for model "/home/a/Prometheus/Simulator/gazebo_simulator/models/race_track"
[Err] [InsertModelWidget.cc:426] Missing model.config for model "/home/a/Prometheus/Simulator/gazebo_simulator/models/texture"
[Err] [InsertModelWidget.cc:426] Missing model.config for model "/home/a/Prometheus/Simulator/gazebo_simulator/models/texture_amov"

**Comment by 473867143** [comment]
这个不影响的，编译是为了之后用roslaunch启动

**Comment by b369147** [comment]
嗯嗯，感谢



---Original---
