### ISSUE TITLE
关于运行出现 MODE: Unsupported FCU的问题

### ISSUE THREAD

**Issue by lzh-awesome** [amov-lab/Prometheus#110]
运行launch文件出现以下错误，gazebo模型里用键盘控制飞机，飞机不起飞请问是什么原因呢？？

[ERROR] [1615635398.051488138, 13324.424000000]: MODE: Unsupported FCU
[ WARN] [1615635403.059604673, 13328.328000000]: CMD: Command 400 -- wait ack timeout

**Comment by SiddharthJ25** [comment]
Hi, I am having the same issue. Did you resolve it? Also, my drone state in the second terminal is "Unconnected".

**Comment by GanAH** [comment]
有大神出来解答吗，飞机无法起飞

**Comment by lzh-awesome** [comment]
> 有大神出来解答吗，飞机无法起飞

我已经解决了可以看下这个链接：https://blog.csdn.net/zhihao8013/article/details/115334822?spm=1001.2014.3001.5501
或者这个链接：https://bbs.amovlab.com/forum.php?mod=viewthread&tid=27139&extra=

**Comment by lzh-awesome** [comment]
@GanAHE @SiddharthJ25 我已经解决了可以看下这个链接：https://blog.csdn.net/zhihao8013/article/details/115334822?spm=1001.2014.3001.5501
或者这个链接：https://bbs.amovlab.com/forum.php?mod=viewthread&tid=27139&extra=

**Comment by potato77** [comment]
请使用专用的prometheus_px4固件。
如果还有问题，建议重新编译一下固件。

**Comment by Xue-JW** [comment]
https://discuss.px4.io/t/pxh-shell-doesnt-launch-when-i-run-with-gazebo/19886/2
