### ISSUE TITLE
电脑配置要求咨询

### ISSUE THREAD

**Issue by unravelwool** [amov-lab/Prometheus#117]
您好，
我们实验室打算使用您开源的该仿真平台进行集群仿真。我想咨询一下用于仿真的电脑的配置大概是什么样子的？
比如说 CPU型号最低是多少，主频、核数、内存是多少合适，GPU型号最低是多少？
另外想问一下您团队的仿真电脑的配置大概是怎样的呢？

**Comment by potato77** [comment]
一般来说，Gazebo仿真比较吃CPU，如果显示器分辨率较高，也需要显卡不能太差。
如果是多机仿真（10架以上），一次性启动会很卡，建议分次启动即可。
