### ISSUE TITLE
fast_planner仿真问题

### ISSUE THREAD

**Issue by Foreveraa** [amov-lab/Prometheus#121]
prometheus运行fast_planner中的rgbd仿真  会报错
运行的指令是
![image](https://user-images.githubusercontent.com/51939403/119454191-dc970580-bd6a-11eb-9c00-fdb43d224b4b.png)
出现的错误是
![image](https://user-images.githubusercontent.com/51939403/119454219-e4ef4080-bd6a-11eb-9d55-81a6e3ab92b8.png)

[ERROR] [1621926799.574101414, 61.400000000]: Ignoring transform from authority "unknown_publisher" with frame_id and child_frame_id  "world" because they are the same
[ERROR] [1621926799.574193055, 61.400000000]: Ignoring transform from authority "unknown_publisher" with frame_id and child_frame_id  "world" because they are the same

另一个终端显示no map
![image](https://user-images.githubusercontent.com/51939403/119455135-e2d9b180-bd6b-11eb-8da8-717593e44e19.png)
rviz中给一个目标点 无人机不会运动，上面的错误该如何解决

**Comment by anning808** [comment]
你好你最后怎么解决的阿

**Comment by Foreveraa** [comment]
目前还没有解决掉 @anning808

**Comment by potato77** [comment]
FastPlanner暂时不支持，还在开发中。

**Comment by pzx-Id** [comment]
解决了吗？
