### ISSUE TITLE
关于编译报错

### ISSUE THREAD

**Issue by Jisooyaaa** [amov-lab/Prometheus#122]
您好！在编译Prometheus项目时，提示CMakeFiles/create_board_charuco.dir/cpp_nodes/create_board_charuco.cpp.o：在函数‘main’中：
对‘cv::aruco::getPredefinedDictionary(cv::aruco::PREDEFINED_DICTIONARY_NAME)’未定义的引用
对‘cv::aruco::CharucoBoard::create(int, int, float, float, cv::Ptr<cv::aruco::Dictionary> const&)’未定义的引用
之前的安装步骤按照github上的wiki推荐步骤，请问如何避免该问题？
![2021-05-30 21-56-48 的屏幕截图](https://user-images.githubusercontent.com/55435925/120107184-9b4f8d00-c192-11eb-99b0-75717a317333.png)

**Comment by 473867143** [comment]
可能是你的opencv版本不正确，可以参考下面 https://github.com/amov-lab/Prometheus/wiki/Q&A%E6%B1%87%E6%80%BB#detection%E6%A8%A1%E5%9D%97%E7%BC%96%E8%AF%91%E9%97%AE%E9%A2%98%E9%BB%98%E8%AE%A4%E5%AE%89%E8%A3%85%E4%BA%86opencv4%E6%97%B6
