### ISSUE TITLE
PID位置环控制器出错

### ISSUE THREAD

**Issue by Dnadadad** [amov-lab/Prometheus#123]
使用官方给的PID位置环控制器时，其轨迹跑的很偏，用其他的官方给的算法控制效果都很差，下面是launch文件（并未修改
）、终端的内容以及轨迹，请问怎么解决
![launch截图1](https://user-images.githubusercontent.com/57580240/120143755-4dc73480-c213-11eb-89cf-a681c58b98d3.png)
![launch截图2](https://user-images.githubusercontent.com/57580240/120143757-4dc73480-c213-11eb-94b2-a3c4e49e5b5c.png)
![终端截图1](https://user-images.githubusercontent.com/57580240/120143754-4dc73480-c213-11eb-86aa-c7fc3bf6de43.png)
![终端截图2](https://user-images.githubusercontent.com/57580240/120143756-4dc73480-c213-11eb-9591-da1db69e445a.png)
![轨迹图](https://user-images.githubusercontent.com/57580240/120143764-50298e80-c213-11eb-9940-6bc042f0ae02.png)

**Comment by potato77** [comment]
看到有一个WARN了吗，CPID不支持轨迹追踪。
我现在将默认控制算法改为传统PID了，你直接启动这个launch再试试
