### ISSUE TITLE
Error while running "roslaunch prometheus_gazebo sitl.launch"

### ISSUE THREAD

**Issue by boyagesmile** [amov-lab/Prometheus#124]
Takeoff_height   : 1 [m] 
Disarm_height    : 0.25 [m] 
Land_speed       : 0.2 [m/s] 
Land_mode        : 1
geo_fence_x : -50 [m]  to  50 [m]
geo_fence_y : -50 [m]  to  50 [m]
geo_fence_z : -0.5 [m]  to  50 [m]
RLException: Roslaunch got a 'No such file or directory' error while attempting to run:

gnome-terminal --tab -- /root/Prometheus/devel/lib/prometheus_station/ground_station __name:=ground_station __log:=/root/.ros/log/d7766c8c-c52e-11eb-856b-0242ac110002/ground_station-14.log

Please make sure that all the executables in this command exist and have
executable permission. This is often caused by a bad launch-prefix.
The traceback for the exception was written to the log file
[ground_station-14] killing on exit
[px4_sender-13] killing on exit
[px4_pos_estimator-12] killing on exit
[tf_2Dlidar-10] killing on exit
[tf_realsense_camera-8] killing on exit
[tf_3Dlidar-9] killing on exit
[tf_slam2map-11] killing on exit
[mavros-6] killing on exit
[vehicle_spawn_9f7a3407a00f_26588_4305379817276566708-5] killing on exit
[tf_world_map-7] killing on exit
[gazebo_gui-4] killing on exit
[gazebo-3] killing on exit
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/gazebo_ros/spawn_model", line 239, in <module>
    exit_code = sm.run()
  File "/opt/ros/melodic/lib/gazebo_ros/spawn_model", line 189, in run
    self.args.gazebo_namespace)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/gazebo_ros/gazebo_interface.py", line 16, in spawn_sdf_model_client
    rospy.wait_for_service(gazebo_namespace+'/spawn_sdf_model')
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 166, in wait_for_service
    raise ROSInterruptException("rospy shutdown")
rospy.exceptions.ROSInterruptException: rospy shutdown
^C[sitl-2] killing on exit
ERROR [px4] Startup script returned with return value: 2
[rosout-1] killing on exit

**Comment by potato77** [comment]
不是很清楚，可以在提供一些信息吗？
以及这一句能否正常运行？
make amovlab_sitl_default gazebo
