### ISSUE TITLE
户外测试可能碰到的高度问题

### ISSUE THREAD

**Issue by L3Y1Q2** [amov-lab/Prometheus#125]
代码中建议在户外测试时使用相对高度是在GLOBAL坐标系下的，但是发送的期望位置是LOCAL坐标系下的，当两个坐标系Z轴值差不多时问题不大，但是存在两个Z值不同的情况从而导致起飞高度不对。
例如：无人机在地面静止不动，LOCAL坐标系Z轴值漂移不为0（正常情况下就是会漂，而且漂的还不小），但是GLOBAL坐标系下的相对高度是为0的，存在不一致，在使用过程中需要注意。

**Comment by potato77** [comment]
确实存在这个问题，户外建议使用RTK或者起飞前记录高度保证相对高度准确。
