### ISSUE TITLE
运行roslaunch prometheus_experiment control_ground.launch出错

### ISSUE THREAD

**Issue by ooahahz** [amov-lab/Prometheus#127]
我在启动这个roslaunch prometheus_experiment control_ground.launch文件的时候，显示在[prometheus_experiment]包中不是一个启动文件，请问是什么原因呢？
![image](https://user-images.githubusercontent.com/70670571/123120094-a25a7a00-d476-11eb-8de4-ab0aa1b92cd1.png)
![image](https://user-images.githubusercontent.com/70670571/123120158-ad150f00-d476-11eb-9bcf-95ca9a20bbfb.png)

**Comment by 473867143** [comment]
没有编译实验包，再Prometheus中有编译实验包的脚本  **./compile_experiment.sh**

**Comment by potato77** [comment]
这个是系统没有找到功能包，可能的原因：1、没编译 2、没source环境变量

可以通过rospack list 看一下有没有prometheus_experiment这个功能包，没有的话是不可能可以运行的
