### ISSUE TITLE
make amovlab_sitl_default gazebo 报错

### ISSUE THREAD

**Issue by Richard-LXA** [amov-lab/Prometheus#131]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GSTREAMER_LIBRARIES (ADVANCED)
    linked by target "gazebo_airship_dynamics_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_airspeed_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_groundtruth_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "physics_msgs" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "std_msgs" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_usv_dynamics_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_parachute_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_irlock_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_geotagged_images_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_lidar_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_multirotor_base_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_wind_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "sensor_msgs" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_gst_camera_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "mav_msgs" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_controller_interface" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_video_stream_widget" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_gps_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_opticalflow_mockup_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_opticalflow_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_uuv_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "nav_msgs" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_sonar_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_vision_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_gimbal_controller_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_imu_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_mavlink_interface" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_motor_model" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_magnetometer_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_barometer_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "LiftDragPlugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo
    linked by target "gazebo_catapult_plugin" in directory /home/ruoyo/Atlas/prometheus_px4/Tools/sitl_gazebo

**Comment by SherryC98** [comment]
sudo apt-get install libgstreamer-plugins-base1.0-dev
