### ISSUE TITLE
固定翼代码问题

### ISSUE THREAD

**Issue by yufeng-Lu520** [amov-lab/Prometheus#133]
固定翼可以直接使用吗，px4_pos_att_controller.cpp里面的代码，例如
command_fsc.set_takeoff_position()
command_fsc.printf_param()、

command_to_mavros.h里没set_takeoff_position printf_param等。

**Comment by potato77** [comment]
PX4支持固定翼，但是如果要用Prometheus控制固定翼，应该需要做一些修改。
另外，PX4中的固定翼对OFFBOARD模式支持不是很多，只能提供位置点控制，不能提供更底层的指令了。

不过，mavros本身只是一个通信工具包，发送的是mavlink指令，只要PX4有这个mavlink接口，就可以使用（但command_to_mavros.h中不一定包含了相应的指令）。

**Comment by yufeng-Lu520** [comment]
您的代码里command_fsc.set_takeoff_position()没有set_takeoff_position 的功能，但是在px4_pos_att_controller里却调用了，是暂时还没完成这部分代码还是什么原因呢
