### ISSUE TITLE
仿真导入自建地图问题

### ISSUE THREAD

**Issue by KriegPyx** [amov-lab/Prometheus#134]
**导入自建的地图进行避障仿真，发现地图并没有真实导入，不知道下面方法哪里有问题，该如何解决？**
**想使用自建的地图在prometheus运行fast_planner中的3dlidar仿真，运行指令为：**
![指令](https://user-images.githubusercontent.com/87682987/126288077-8a9f35eb-e2fe-439b-ab7b-581c7f1701d7.png)
**对应的launch文件修改部分如下：**
![1](https://user-images.githubusercontent.com/87682987/126288124-ee8fe1ca-7004-4783-960c-c22f0f642c9d.png)

![2](https://user-images.githubusercontent.com/87682987/126288322-ee453498-f652-499b-ba5c-31cf4d49a00e.png)

![image](https://user-images.githubusercontent.com/87682987/126288410-b41ff4c6-fde4-415f-b1d2-53faf82b38e3.png)

**启动后rviz显示雷达探测不到地图，gazebo显示也是空的，进行仿真时候，飞机会穿墙而过**
![roslaunch启动](https://user-images.githubusercontent.com/87682987/126288718-c4400ae9-3b94-4166-8966-0105b7f1b473.png)

**world文件导入地图的内容如下**
![image](https://user-images.githubusercontent.com/87682987/126289634-210ff96b-27a2-47d4-a5bc-feb939489b8f.png)

**单独运行world文件，在gazebo当中发现地图能正常显示**
![单独启动](https://user-images.githubusercontent.com/87682987/126289002-a54c8057-8ee4-4a91-90f1-3c62e4969480.png)

**Comment by potato77** [comment]
从你发的图片来看，map.world好像加载了（如果gazebo加载地图失败是会报错的）？是一些很奇怪的点（最后一张图黑色的部分），你map.world的写法我没用过，不清楚是否是正确的。

从rviz中真实点云显示的效果来看，第一张图的绿色部分是和第二张图的黑色部分是一致的吧？

最后，飞机不避障的原因是3维激光雷达没有检测到障碍物，因为gazebo的world没有设置collision导致激光雷达无法检测到（可以通过rviz中显示3维激光雷达的检测结果来测试）。
