### ISSUE TITLE
Octomap例程里无人机起飞后直接飞走了

### ISSUE THREAD

**Issue by kavinwkp** [amov-lab/Prometheus#135]
![11](https://user-images.githubusercontent.com/71803246/126316776-81d23063-a695-4d3f-937b-862d00c56de4.png)
程序编译没问题，运行roslaunch prometheus_gazebo sitl_octomap.launch后正常没报错，运行rosrun prometheus_control terminal_control控制程序解锁飞机并起飞后就直接往上面飞走了，可能是定位出问题，但不知道怎么解决

**Comment by potato77** [comment]
先运行一下最基本的启动脚本能否正常运行，roslaunch prometheus_gazebo sitl.launch。

如果是同样情况的话，应该是仿真环境配置出问题了，PX4没有收到定位数据，就会导致直接飞上天。
