### ISSUE TITLE
安装Ubuntu系统兼容性问题

### ISSUE THREAD

**Issue by flytohign** [amov-lab/Prometheus#141]
安装阿木实验室的Ubuntu系统，进入到system installer之后，就没反应了，有什么合适的解决方法嘛？
![阿木Ubuntu安装](https://user-images.githubusercontent.com/78900282/128111633-3f386cf4-d0ef-4934-bb78-44293b74179a.jpg)

**Comment by potato77** [comment]
这个问题建议在群里问一下可能更好一点，因为根据电脑不同，可能会有不同的原因。

我本人没装过这个镜像。
