### ISSUE TITLE
启动集群launch文件时的错误

### ISSUE THREAD

**Issue by MaverickCCC** [amov-lab/Prometheus#142]
![image](https://user-images.githubusercontent.com/60563312/127986673-69136db5-b994-45a4-ab96-06b668072258.jpeg)
**图1**

Gazebo集群仿真运行测试，启动launch文件后提示图1中的udp_port的错误，出现2+1个终端，确实打印信息终端，控制终端输入指令后无人机可以飞行但是不能打印信息。
想请教一下可能是哪里出问题了？

**Comment by potato77** [comment]
这个报错我也遇到过，但似乎不影响飞行。

具体是启动的那个launch文件，不能打印什么信息呢？ @Boshen97

**Comment by MaverickCCC** [comment]
感谢戚博的回复，udp这个问题不大我就放心了。


我具体启动的是swarm_4uav那个launch文件，我看到你集群直播课里启动后有3个显示终端和1个控制终端，课上你说第三个显示终端会打印出无人机的一些信息。


我这边虽然可以飞行，但唯独少了第三个显示终端，除了这个udp端口的报错外，没有其他报错，所以不知道什么原因导致这个终端没有出现，不知道戚博是否遇到过？


| |
陈兆通
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年08月4日 ***@***.***> 写道：

这个报错我也遇到过，但似乎不影响飞行。

具体是启动的那个launch文件，不能打印什么信息呢？ @Boshen97

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by potato77** [comment]
你看看终端是否打印齐了四架飞机的数据呢？
如果功能上没有问题的话，可能是后来精简了一下终端打印吧。
@Boshen97 协助解决一下吧
