### ISSUE TITLE
运行ego_planner出问题。

### ISSUE THREAD

**Issue by pzx-Id** [amov-lab/Prometheus#144]
![2021-08-07 15-55-59 的屏幕截图](https://user-images.githubusercontent.com/73288354/128593752-1529cdc1-50ec-4154-b043-5eb68ccc5cc3.png)
![2021-08-07 15-57-00 的屏幕截图](https://user-images.githubusercontent.com/73288354/128593754-20fc27ca-6393-4ed3-be3a-17415c23a74e.png)
运行ego_planner发现上面的错误，控制不了无人机。（可能是mavros没连上）
不知道是我的运行问题还是怎么的。
该怎么解决呢？

**Comment by potato77** [comment]
就是mavros没连接上，切换px4代码分支了么？

**Comment by pzx-Id** [comment]
应该是没有切换px4代码分支。应该怎么切换px4代码分支呢？

**Comment by pzx-Id** [comment]
切换了px4代码分支后还是存在这个问题。 @potato77

**Comment by potato77** [comment]
我这边仿真是正常的，你再检查一下PX4脚本还有启动文件吧

![image](https://user-images.githubusercontent.com/11450591/129028995-8cba3fd4-e133-4d72-a0cd-831e3ba786e6.png)

**Comment by pzx-Id** [comment]
好的，谢谢。我运行的时候，第一次是mavros正常的，但是不能控制无人机。
再第二次运行后就出现了之前那种情况。

**Comment by pzx-Id** [comment]
再次打扰您一下，我这个连接都没问题，但是无人机没有反应，飞不起来。 状态是connected，但是是disarmed，这个应该怎么解决呢？
