### ISSUE TITLE
使用px4开发防撞模式出现问题

### ISSUE THREAD

**Issue by brain726** [amov-lab/Prometheus#146]
我是使用多线激光雷达开发的，将得到的点云数据滤波，得到36个方向的距离，并使用/mavros/obstacle/send发送到飞控，飞控可以接收到距离数据，但是飞控无法判断距离数据的方向。mavlink数据如下图所示。

![微信图片_20210811194452](https://user-images.githubusercontent.com/53047509/129023335-6e3bc8ad-58ae-43ae-b7f3-ffff908dab04.png)
可以看到有关角度的数据飞控并没有收到，但是我的确通过mavros发送了数据，请问这是什么原因

**Comment by potato77** [comment]
这个不是Prometheus开发问题哦，建议在PX4 issue区提问。
