### ISSUE TITLE
 编译planning、slam等模块时的报错问题（已看过所有相关issues）

### ISSUE THREAD

**Issue by MaverickCCC** [amov-lab/Prometheus#147]
planning和ego编译错误提示在：[ 97%] Built target traj_server  为图1和2所示。

slam编译错误提示：./compile_slam.sh: 第 5 行: cd: Modules/slam/config/Vocabulary: 没有那个文件或目录
tar: ORBvoc.txt.tar.gz：无法 open: 没有那个文件或目录
tar: Error is not recoverable: exiting now

![2021-08-12 14-47-44 的屏幕截图](https://user-images.githubusercontent.com/60563312/129151560-4fdd6dcc-cb62-46c7-9a0c-2fbc028877de.png)
**图1**
![2021-08-12 14-48-23 的屏幕截图](https://user-images.githubusercontent.com/60563312/129151608-ec6dc3dc-aa2e-4966-8952-d63753818f49.png)
**图2**

 
我已查阅过其他功能包编译的issues，同时试过其余模块单独编译没有其他问题。
想知道以上问题可以如何解决，谢谢！

**Comment by tugepaopaoo** [comment]
遇到了相同的问题

**Comment by tugepaopaoo** [comment]
我这边在编译planning和ego模块出现“未定义的引用”报错后，将Prometheus/build中编译生成的ego_planner、planning文件夹分别删除，然后再重新编译，可以编译成功。

**Comment by 473867143** [comment]
> planning和ego编译错误提示在：[ 97%] Built target traj_server 为图1和2所示。
> 
> slam编译错误提示：./compile_slam.sh: 第 5 行: cd: Modules/slam/config/Vocabulary: 没有那个文件或目录
> tar: ORBvoc.txt.tar.gz：无法 open: 没有那个文件或目录
> tar: Error is not recoverable: exiting now
> 
> ![2021-08-12 14-47-44 的屏幕截图](https://user-images.githubusercontent.com/60563312/129151560-4fdd6dcc-cb62-46c7-9a0c-2fbc028877de.png)
> **图1**
> ![2021-08-12 14-48-23 的屏幕截图](https://user-images.githubusercontent.com/60563312/129151608-ec6dc3dc-aa2e-4966-8952-d63753818f49.png)
> **图2**
> 
> 我已查阅过其他功能包编译的issues，同时试过其余模块单独编译没有其他问题。
> 想知道以上问题可以如何解决，谢谢！

slam编译报错不影响使用。

**Comment by 473867143** [comment]
> 我这边在编译planning和ego模块出现“未定义的引用”报错后，将Prometheus/build中编译生成的ego_planner、planning文件夹分别删除，然后再重新编译，可以编译成功。

对，最好把build和devel编译文件删掉，然后再重新编译，先编译planning再编译ego
