### ISSUE TITLE
编译control模块报错，未定义battery数据类型

### ISSUE THREAD

**Issue by tugepaopaoo** [amov-lab/Prometheus#148]
1、编译control模块报错，未定义battery数据类型

![2021-08-17 10-03-04屏幕截图](https://user-images.githubusercontent.com/74280737/129655380-4b7c682c-dc1c-456f-847d-ecb8808e2f3a.png)

2、然后自己在UgvState.msg中添加battery数据类型
![2021-08-17 10-05-46屏幕截图](https://user-images.githubusercontent.com/74280737/129655159-d2e4e02e-5cf2-435c-8f6f-195c3e8cf4de.png)

3、再次运行，编译通过

**Comment by potato77** [comment]
主分支中bug已修复，感谢
