### ISSUE TITLE
多无人机控制无人机无反应

### ISSUE THREAD

**Issue by lianbashou123** [amov-lab/Prometheus#156]
![mmexport1632368310891](https://user-images.githubusercontent.com/88788972/134452960-7325e7e4-f253-45f8-aa74-67b37c1cd9dc.jpg)
![5602aa6bc15ebadd](https://user-images.githubusercontent.com/88788972/134452966-d85ac8d9-ee6e-46ff-919d-1b0d297ea750.jpg)
已经切换到了Prometheus_swarm分支，但是跑代码，切换offboard和take off都没反应无人机，无人机和无人车混合的时候无人车有反应，是不是我环境有问题？之前安装过Firmware，后来直接删除了安装了阿木的Prometheus_px4，室外定点sitl  control那些都没问题，就是多无人机控制没反应

**Comment by amovlab-official** [comment]
在群组里面是否已经解决，如果不麻烦，解决方式整理一下，放在issue下面；谢谢支持

**Comment by potato77** [comment]
已在微信群回复解决，问题是固件版本问题，没有正确的切换到swarm分支
