### ISSUE TITLE
使用 RTSP 推流ROS 图像失败

### ISSUE THREAD

**Issue by wuhaixiang** [amov-lab/Prometheus#159]
环境： vmware
系统：ubuntu 18.04 
运行脚本 rtsp_steam.launch
错误地址：
def main(width,height,port,factory_name):
    global out_send
    out_send = cv2.VideoWriter('appsrc is-live=true ! videoconvert ! \
                                omxh264enc bitrate=12000000 ! video/x-h264, \
                                stream-format=byte-stream ! rtph264pay pt=96 ! \
                                udpsink host=192.168.86.141 port=5400 async=false',
                                cv2.CAP_GSTREAMER,30, (width,height), True)
 
    if not out_send.isOpened():
        print('VideoWriter not opened')
        exit(0)
提示 out_send 没有打开，程序退出

**Comment by huangwen0907** [comment]
I have the same problem, if you have some good idea, please let me know. TKS.

**Comment by likehengqq** [comment]
仅可以用于Nvidia TX2与NX平台，通过Nvidia Gstreamer进行编码

**Comment by potato77** [comment]
X86可以试一下这个教程，https://github.com/amov-lab/Prometheus/wiki/%E5%B0%86%E6%A3%80%E6%B5%8B%E7%BB%93%E6%9E%9C(ROS%E5%9B%BE%E5%83%8F)%E6%8E%A8%E6%B5%81%E5%88%B0%E5%9C%B0%E9%9D%A2%E7%AB%99
