### ISSUE TITLE
./ego_test.sh

### ISSUE THREAD

**Issue by evehuang** [amov-lab/Prometheus#169]
请问大家promethues里面的ego_planner都跑通了吗？大家运行./ego_test.sh会出现以下错误吗？
![mmexport1634358614620](https://user-images.githubusercontent.com/33803475/137574225-97d7506e-06e5-42bf-ae53-3ff5223e8ea1.jpg)

**Comment by evehuang** [comment]
已解决

**Comment by Hang-Shi** [comment]
现在已经没有ego_test.sh这个文件了，请问最新的launch_ego_planner应该如何启动呢？

**Comment by pengyuwang35** [comment]
> 已解决
您好，我遇到了相同的问题all processes on machine have died, roslaunch will exit，请问您如何解决的呢，谢谢。
