### ISSUE TITLE
roslaunch prometheus_gazebo sitl.launch

### ISSUE THREAD

**Issue by HazeOcean** [amov-lab/Prometheus#174]
roslaunch prometheus_gazebo sitl.launch
终端显示unconnected

**Comment by HazeOcean** [comment]
> 可能的原因有很多，执行make amovlab_sitl_default gazebo这句能够正常加载出模型且进行控制吗？

能够加载出模型，但是没有提供控制的终端，也会报missing model的错

**Comment by Handsome-B** [comment]
请问你解决这个问题了吗，我和你一模一样，前面编译没有任何问题了，就是最后unconnected

**Comment by Handsome-B** [comment]
找到我自己的问题了，在/.bashrc文件里添加prometheus_px4文件路径的时候有地方打错了

**Comment by HazeOcean** [comment]
> 找到我自己的问题了，在/.bashrc文件里添加prometheus_px4文件路径的时候有地方打错了

恭喜，我也发现是教程的路径给的不对
