### ISSUE TITLE
运行 rosrun prometheus_control terminal_control后输入指令无法起飞

### ISSUE THREAD

**Issue by Long-Wu-code** [amov-lab/Prometheus#181]
窗口显示
[NORMAL][px4_sender]:The Drone is in OFFBOARD Mode already...
[NORMAL][px4_sender]:The Drone is armd already...

gazebo中的无人机机翼旋转，但是无人机没有起飞

**Comment by 473867143** [comment]
可能只输入了999解锁且切换offboard模式，没有输入takeoff指令。你可以将各个窗口的截图发一下
