### ISSUE TITLE
集群的全局和局部路径规划什么时候能出DEMO

### ISSUE THREAD

**Issue by gukang33** [amov-lab/Prometheus#182]
集群的路径规划什么时候能出DEMO，非常期待

**Comment by 473867143** [comment]
可以参考一下Wiki里面的launch，这个是基于局部避障APF方法  https://github.com/amov-lab/Prometheus/wiki/Promehteus%E4%BB%BF%E7%9C%9F%E5%8A%9F%E8%83%BD#launch_swarm%E6%96%87%E4%BB%B6%E5%A4%B9%E9%9B%86%E7%BE%A4%E6%8E%A7%E5%88%B6%E7%9B%B8%E5%85%B3 

全局EGO规划目前也有相应的demo，稍后会补充到Wiki之中
