### ISSUE TITLE
集群数量增加到10，数量和阵型也设定了，但运行之后编队切换显示Critical navigation failure! Check sensor calibration

### ISSUE THREAD

**Issue by gukang33** [amov-lab/Prometheus#183]
集群数量增加到10，数量和阵型也设定了，但运行之后编队切换显示Critical navigation failure! Check sensor calibration
怎么解决，还有其他参数要更改么？

INFO  [commander] Takeoff detected
INFO  [commander] Takeoff detected
ERROR [commander] Critical navigation failure! Check sensor calibration
ERROR [commander] Critical navigation failure! Check sensor calibration
ERROR [commander] Critical navigation failure! Check sensor calibration
WARN  [mc_pos_control] invalid setpoints
WARN  [mc_pos_control] Failsafe: blind land
WARN  [mc_pos_control] invalid setpoints
WARN  [mc_pos_control] Failsafe: blind land
----> Out of the geo fence, the drone is landing...
WARN  [commander] Failsafe enabled: no local position
INFO  [commander] Failsafe mode activated
[ WARN] [1636254697.502834849, 30.148000000]: CMD: Unexpected command 176, result 0
----> Out of the geo fence, the drone is landing...
----> Out of the geo fence, the drone is landing...
----> Out of the geo fence, the drone is landing...
----> Out of the geo fence, the drone is landing...
INFO  [ecl/EKF] 31332000: reset velocity to zero

**Comment by potato77** [comment]
不是很清楚具体原因，建议可以先从数量少的开始测试，排查一下原因
