### ISSUE TITLE
圆环实验有问题

### ISSUE THREAD

**Issue by A-ppIes** [amov-lab/Prometheus#187]
环境，固件已全部配置好。在运行圆环的launch文件，输入1让其起飞，但是无人机飞到一点高度后立马降落。
自己在排查的过程中发现是模型文件的问题，更改为 p450.sdf 后飞行正常。
自主降落也是，起飞后一直向上飞。望排查下，谢谢

**Comment by 473867143** [comment]
请问使用的是docker吗？有过类似的问题，不过都是偶然遇到。
