### ISSUE TITLE
ERROR: cannot launch node of type [prometheus_detection/kcf_tracker]

### ISSUE THREAD

**Issue by akamob** [amov-lab/Prometheus#190]
当我运行**框选识别KCF**的命令: **roslaunch prometheus_gazebo sitl_kcf_detection.launch**
出现以下错误讯息:
ERROR: cannot launch node of type [prometheus_detection/kcf_tracker]: Cannot locate node of type [kcf_tracker] in package [prometheus_detection]. Make sure file exists in package path and permission is set to executable (chmod +x)
![q1](https://user-images.githubusercontent.com/49118957/142886792-7da1de67-d891-46ce-91f7-1454a4bed284.png)

程式虽然可以执行，但是却显示**Lost the Target**且**无法弹出交互框**。
![q2](https://user-images.githubusercontent.com/49118957/142886835-ae941f98-e78b-4a8f-932c-bb208b05ef11.png)

无法弹出交互框是因为上面的错误吗？
是的话我想向您请教如何debug。

谢谢您!

**Comment by 473867143** [comment]
报错是找不到prometheus_detection包，可以重新编译一遍 ,执行一下 https://github.com/amov-lab/Prometheus/blob/master/compile_all.sh
