### ISSUE TITLE
数字识别出错

### ISSUE THREAD

**Issue by dorothy1122** [amov-lab/Prometheus#194]
运行数字识别的roslaunch文件，发现**[digitnum_det-16]process has died [pid 27602, exit code 1,...**的问题，在python2.7/python3.6运行环境下都有问题，pytorch_mnist_det.py代码编译没问题，应该是torch的问题，但是已经安装了pytorch，想问一下在pytorch_mnist_det.py里面是怎么找torch？

**Comment by dorothy1122** [comment]
![2021-12-01 22-06-59 的屏幕截图](https://user-images.githubusercontent.com/65701107/144249027-f4ee4495-6480-49ed-8f6b-1a60a3a0092a.png)

**Comment by dorothy1122** [comment]
![2021-12-01 22-06-19 的屏幕截图](https://user-images.githubusercontent.com/65701107/144249069-ee94d737-041e-4fe9-adf0-875d000ed4cb.png)

**Comment by jario-jin** [comment]
`No module named builtins`，应该是需要运行`pip install future`
如果想看`torch`有没有问题，需要再`terminal`里运行`python/python3`，然后在里面输出`import torch`如果没报错就没问题。

**Comment by dorothy1122** [comment]
> 

torch没问题，环境是python3.6.13，torch版本是1.4.0+cpu，运行脚本还是有错误，麻烦你们看下是不是代码问题呢？

**Comment by dorothy1122** [comment]
![2021-12-02 18-59-21 的屏幕截图](https://user-images.githubusercontent.com/65701107/144412439-72fd7004-ab70-4436-973b-d067d251241e.png
![2021-12-02 19-01-31 的屏幕截图](https://user-images.githubusercontent.com/65701107/144412446-2a3de0f3-02be-4026-aec5-c20404e348f4.png)
)

**Comment by dorothy1122** [comment]
![2021-12-02 18-59-21 的屏幕截图](https://user-images.githubusercontent.com/65701107/144412486-4ed590da-5f81-4c81-87b9-03f27e9ccaef.png)

**Comment by dorothy1122** [comment]
![2021-12-02 19-01-31 的屏幕截图](https://user-images.githubusercontent.com/65701107/144412501-fd038806-70f9-4f43-aa3d-a3609eaaf812.png)

**Comment by bzbsng** [comment]
我也有同样的问题，请问解决了吗

**Comment by dorothy1122** [comment]
> 我也有同样的问题，请问解决了吗

解决了，px4的问题，安装px4的时候中间有一步我之前用sudo make去做的，装出来编译也没有问题，但是我换了一种安装的方式，再去运行这个就没有问题了

**Comment by bzbsng** [comment]
> > 我也有同样的问题，请问解决了吗
> 
> 解决了，px4的问题，安装px4的时候中间有一步我之前用sudo make去做的，装出来编译也没有问题，但是我换了一种安装的方式，再去运行这个就没有问题了

我安装px4就是按照这个wiki里面给的步骤，你说的换了一种安装方式有没有参考网站啊，能不能发一下，感谢感谢!
