### ISSUE TITLE
编译ego_planner报错，未定义使用，链接问题。catkin_make --source Modules/ego_planner --build build/ego_planner

### ISSUE THREAD

**Issue by Pupillen** [amov-lab/Prometheus#197]
catkin_make --source Modules/ego_planner --build build/ego_planner

log如下：
Base path: /home/ztr/workspace/learn_mavros/amov环境/Prometheus
Source space: /home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner
Build space: /home/ztr/workspace/learn_mavros/amov环境/Prometheus/build/ego_planner
Devel space: /home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel
Install space: /home/ztr/workspace/learn_mavros/amov环境/Prometheus/install
####
####
####
####
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_LQRTrajectory
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_Gains
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_Serial
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_StatusData
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_PositionCommand
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_Odometry
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_PPROutputData
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_TRPYCommand
[  0%] Built target nav_msgs_generate_messages_cpp
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_OutputData
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_Corrections
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_SO3Command
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_AuxCommand
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_PolynomialTrajectory
[  7%] Built target quadrotor_msgs_generate_messages_cpp
[  8%] Built target decode_msgs
[  9%] Built target encode_msgs
[  9%] Built target nav_msgs_generate_messages_py
[  9%] Built target geometry_msgs_generate_messages_py
[ 17%] Built target quadrotor_msgs_generate_messages_py
[ 17%] Built target nav_msgs_generate_messages_lisp
[ 17%] Built target geometry_msgs_generate_messages_lisp
[ 24%] Built target quadrotor_msgs_generate_messages_lisp
[ 24%] Built target geometry_msgs_generate_messages_eus
[ 24%] Built target nav_msgs_generate_messages_eus
[ 32%] Built target quadrotor_msgs_generate_messages_eus
[ 32%] Built target nav_msgs_generate_messages_nodejs
[ 32%] Built target geometry_msgs_generate_messages_nodejs
[ 39%] Built target quadrotor_msgs_generate_messages_nodejs
[ 39%] Built target quadrotor_msgs_generate_messages
[ 40%] Built target random_forest_new
[ 41%] Built target random_forest
[ 43%] Built target obj_generator
[ 45%] Built target plan_env
[ 46%] Built target path_searching
[ 47%] Built target poscmd_2_odom
[ 48%] Built target pose_utils
[ 48%] Built target sensor_msgs_generate_messages_nodejs
[ 48%] Built target std_msgs_generate_messages_py
[ 48%] Built target std_msgs_generate_messages_nodejs
[ 48%] Built target std_msgs_generate_messages_eus
[ 48%] Built target rosgraph_msgs_generate_messages_py
[ 48%] Built target rosgraph_msgs_generate_messages_nodejs
[ 48%] Built target std_msgs_generate_messages_cpp
[ 48%] Built target rosgraph_msgs_generate_messages_lisp
[ 48%] Built target roscpp_generate_messages_cpp
[ 48%] Built target std_msgs_generate_messages_lisp
[ 48%] Built target rosgraph_msgs_generate_messages_cpp
[ 48%] Built target roscpp_generate_messages_lisp
[ 48%] Built target rosgraph_msgs_generate_messages_eus
[ 48%] Built target roscpp_generate_messages_py
[ 48%] Built target roscpp_generate_messages_nodejs
[ 48%] Built target roscpp_generate_messages_eus
[ 48%] Built target sensor_msgs_generate_messages_py
[ 48%] Built target sensor_msgs_generate_messages_cpp
[ 48%] Built target sensor_msgs_generate_messages_eus
[ 48%] Built target sensor_msgs_generate_messages_lisp
[ 49%] Built target drone_detect
[ 50%] Built target odom_visualization
[ 51%] Built target pcl_render_node
[ 54%] Built target mockamap_node
[ 55%] Built target SO3Control
[ 56%] Built target so3_control_nodelet
[ 58%] Built target control_example
[ 59%] Built target multi_map_visualization
[ 59%] Built target _multi_map_server_generate_messages_check_deps_MultiOccupancyGrid
[ 59%] Built target _multi_map_server_generate_messages_check_deps_SparseMap3D
[ 59%] Built target _multi_map_server_generate_messages_check_deps_MultiSparseMap3D
[ 59%] Built target _multi_map_server_generate_messages_check_deps_VerticalOccupancyGridList
[ 62%] Built target multi_map_server_generate_messages_py
[ 64%] Built target multi_map_server_generate_messages_cpp
[ 66%] Built target multi_map_server_generate_messages_lisp
[ 68%] Built target multi_map_server_generate_messages_eus
[ 70%] Built target multi_map_server_generate_messages_nodejs
[ 70%] Built target multi_map_server_generate_messages
[ 70%] Built target _traj_utils_generate_messages_check_deps_Bspline
[ 70%] Built target _traj_utils_generate_messages_check_deps_MultiBsplines
[ 70%] Built target _traj_utils_generate_messages_check_deps_DataDisp
[ 73%] Built target traj_utils_generate_messages_eus
[ 75%] Built target traj_utils_generate_messages_lisp
[ 76%] Built target traj_utils_generate_messages_cpp
[ 77%] Built target traj_utils_generate_messages_nodejs
[ 79%] Built target traj_utils_generate_messages_py
[ 79%] Built target traj_utils_generate_messages
[ 81%] Built target traj_utils
[ 83%] Built target bspline_opt
[ 83%] Linking CXX executable /home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/ego_planner/traj_server
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/libbspline_opt.so：对‘fast_planner::ObjPredictor::evaluateConstVel(int, double)’未定义的引用
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/libbspline_opt.so：对‘AStar::AstarSearch(double, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>)’未定义的引用
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/libbspline_opt.so：对‘AStar::getPath()’未定义的引用
collect2: error: ld returned 1 exit status
ego-planner-swarm/src/planner/plan_manage/CMakeFiles/traj_server.dir/build.make:502: recipe for target '/home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/ego_planner/traj_server' failed
make[2]: *** [/home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/ego_planner/traj_server] Error 1
CMakeFiles/Makefile2:6324: recipe for target 'ego-planner-swarm/src/planner/plan_manage/CMakeFiles/traj_server.dir/all' failed
make[1]: *** [ego-planner-swarm/src/planner/plan_manage/CMakeFiles/traj_server.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j1" failed
_planner 
Base path: /home/ztr/workspace/learn_mavros/amov环境/Prometheus
Source space: /home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner
Build space: /home/ztr/workspace/learn_mavros/amov环境/Prometheus/build/ego_planner
Devel space: /home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel
Install space: /home/ztr/workspace/learn_mavros/amov环境/Prometheus/install
####
####
####
####
[  0%] Built target nav_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_LQRTrajectory
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_StatusData
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_OutputData
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_PPROutputData
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_Odometry
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_Gains
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_TRPYCommand
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_Corrections
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_Serial
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_PositionCommand
[  0%] Built target nav_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target nav_msgs_generate_messages_eus
[  0%] Built target nav_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target nav_msgs_generate_messages_nodejs
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_AuxCommand
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_SO3Command
[  0%] Built target _quadrotor_msgs_generate_messages_check_deps_PolynomialTrajectory
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  1%] Built target std_msgs_generate_messages_nodejs
[  1%] Built target pose_utils
[  2%] Built target random_forest_new
[  2%] Built target rosgraph_msgs_generate_messages_py
[  2%] Built target std_msgs_generate_messages_py
[  2%] Built target std_msgs_generate_messages_eus
[  3%] Built target rosgraph_msgs_generate_messages_nodejs
[  3%] Built target obj_generator
[  4%] Built target random_forest
[  4%] Built target rosgraph_msgs_generate_messages_lisp
[  4%] Built target std_msgs_generate_messages_cpp
[  4%] Built target rosgraph_msgs_generate_messages_cpp
[  6%] Built target plan_env
[  6%] Built target roscpp_generate_messages_cpp
[  6%] Built target std_msgs_generate_messages_lisp
[  6%] Built target roscpp_generate_messages_lisp
[  6%] Built target rosgraph_msgs_generate_messages_eus
[  6%] Built target roscpp_generate_messages_py
[  6%] Built target roscpp_generate_messages_eus
[  6%] Built target sensor_msgs_generate_messages_py
[  6%] Built target sensor_msgs_generate_messages_eus
[  6%] Built target sensor_msgs_generate_messages_cpp
[  6%] Built target roscpp_generate_messages_nodejs
[  6%] Built target sensor_msgs_generate_messages_lisp
[  7%] Built target SO3Control
[ 10%] Built target mockamap_node
[ 10%] Built target _multi_map_server_generate_messages_check_deps_MultiOccupancyGrid
[ 10%] Built target _multi_map_server_generate_messages_check_deps_VerticalOccupancyGridList
[ 10%] Built target _multi_map_server_generate_messages_check_deps_SparseMap3D
[ 12%] Built target traj_utils
[ 13%] Built target quadrotor_dynamics
[ 13%] Built target _multi_map_server_generate_messages_check_deps_MultiSparseMap3D
[ 16%] Built target waypoint_generator
[ 23%] Built target quadrotor_msgs_generate_messages_cpp
[ 23%] Built target _traj_utils_generate_messages_check_deps_Bspline
[ 23%] Built target _traj_utils_generate_messages_check_deps_MultiBsplines
[ 31%] Built target quadrotor_msgs_generate_messages_py
[ 38%] Built target quadrotor_msgs_generate_messages_lisp
[ 38%] Built target _traj_utils_generate_messages_check_deps_DataDisp
[ 46%] Built target quadrotor_msgs_generate_messages_nodejs
[ 47%] Built target path_searching
[ 49%] Built target multi_map_server_generate_messages_lisp
[ 52%] Built target multi_map_server_generate_messages_py
[ 53%] Built target bridge_node
[ 63%] Built target multi_map_server_generate_messages_cpp
[ 63%] Built target quadrotor_msgs_generate_messages_eus
[ 65%] Built target multi_map_server_generate_messages_eus
[ 66%] Built target decode_msgs
[ 68%] Built target multi_map_server_generate_messages_nodejs
[ 70%] Built target traj_utils_generate_messages_lisp
[ 72%] Built target encode_msgs
[ 74%] Built target traj_utils_generate_messages_eus
[ 75%] Built target traj_utils_generate_messages_nodejs
[ 76%] Built target traj_utils_generate_messages_cpp
[ 78%] Built target traj_utils_generate_messages_py
[ 78%] Built target quadrotor_msgs_generate_messages
[ 78%] Built target multi_map_server_generate_messages
[ 80%] Built target bspline_opt
[ 81%] Built target odom_visualization
[ 83%] Built target multi_map_visualization
[ 83%] Built target poscmd_2_odom
[ 84%] Built target drone_detect
[ 86%] Built target so3_control_nodelet
[ 87%] Built target quadrotor_simulator_so3
[ 88%] Built target control_example
[ 89%] Built target pcl_render_node
[ 89%] Built target traj_utils_generate_messages
[ 96%] Built target rviz_plugins
[ 96%] Linking CXX executable /home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/ego_planner/traj_server
[ 96%] Linking CXX executable /home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/ego_planner/ego_planner_node
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/libbspline_opt.so：对‘fast_planner::ObjPredictor::evaluateConstVel(int, double)’未定义的引用
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/libbspline_opt.so：对‘AStar::AstarSearch(double, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>)’未定义的引用
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/libbspline_opt.so：对‘AStar::getPath()’未定义的引用
collect2: error: ld returned 1 exit status
ego-planner-swarm/src/planner/plan_manage/CMakeFiles/traj_server.dir/build.make:502: recipe for target '/home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/ego_planner/traj_server' failed
make[2]: *** [/home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/ego_planner/traj_server] Error 1
CMakeFiles/Makefile2:6324: recipe for target 'ego-planner-swarm/src/planner/plan_manage/CMakeFiles/traj_server.dir/all' failed
make[1]: *** [ego-planner-swarm/src/planner/plan_manage/CMakeFiles/traj_server.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
CMakeFiles/ego_planner_node.dir/src/ego_replan_fsm.cpp.o：在函数‘ego_planner::EGOReplanFSM::planNextWaypoint(Eigen::Matrix<double, 3, 1, 0, 3, 1>)’中：
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/ego_replan_fsm.cpp:170：对‘ego_planner::PlanningVisualization::displayGlobalPathList(std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >, double, int)’未定义的引用
CMakeFiles/ego_planner_node.dir/src/ego_replan_fsm.cpp.o：在函数‘ego_planner::EGOReplanFSM::readGivenWps()’中：
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/ego_replan_fsm.cpp:123：对‘ego_planner::PlanningVisualization::displayGoalPoint(Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 4, 1, 0, 4, 1>, double, int)’未定义的引用
CMakeFiles/ego_planner_node.dir/src/ego_replan_fsm.cpp.o：在函数‘ego_planner::EGOReplanFSM::callReboundReplan(bool, bool)’中：
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/ego_replan_fsm.cpp:804：对‘ego_planner::PlanningVisualization::displayOptimalList(Eigen::Matrix<double, -1, -1, 0, -1, -1>, int)’未定义的引用
CMakeFiles/ego_planner_node.dir/src/ego_replan_fsm.cpp.o：在函数‘ego_planner::EGOReplanFSM::waypointCallback(boost::shared_ptr<geometry_msgs::PoseStamped_<std::allocator<void> > > const&)’中：
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/ego_replan_fsm.cpp:208：对‘ego_planner::PlanningVisualization::displayGoalPoint(Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 4, 1, 0, 4, 1>, double, int)’未定义的引用
CMakeFiles/ego_planner_node.dir/src/ego_replan_fsm.cpp.o：在函数‘ego_planner::EGOReplanFSM::init(ros::NodeHandle&)’中：
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/ego_replan_fsm.cpp:43：对‘ego_planner::PlanningVisualization::PlanningVisualization(ros::NodeHandle&)’未定义的引用
CMakeFiles/ego_planner_node.dir/src/planner_manager.cpp.o：在函数‘ego_planner::EGOPlannerManager::initPlanModules(ros::NodeHandle&, std::shared_ptr<ego_planner::PlanningVisualization>)’中：
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/planner_manager.cpp:38：对‘GridMap::initMap(ros::NodeHandle&)’未定义的引用
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/planner_manager.cpp:50：对‘AStar::initGridMap(std::shared_ptr<GridMap>, Eigen::Matrix<int, 3, 1, 0, 3, 1>)’未定义的引用
CMakeFiles/ego_planner_node.dir/src/planner_manager.cpp.o：在函数‘ego_planner::EGOPlannerManager::initPlanModules(ros::NodeHandle&, std::shared_ptr<ego_planner::PlanningVisualization>)’中：
/usr/include/c++/7/bits/shared_ptr_base.h:588：对‘AStar::~AStar()’未定义的引用
CMakeFiles/ego_planner_node.dir/src/planner_manager.cpp.o：在函数‘ego_planner::EGOPlannerManager::planGlobalTrajWaypoints(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > > const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&)’中：
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/planner_manager.cpp:459：对‘PolynomialTraj::minSnapTraj(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)’未定义的引用
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/planner_manager.cpp:461：对‘PolynomialTraj::one_segment_traj_gen(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, double)’未定义的引用
CMakeFiles/ego_planner_node.dir/src/planner_manager.cpp.o：在函数‘ego_planner::EGOPlannerManager::planGlobalTraj(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&)’中：
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/planner_manager.cpp:534：对‘PolynomialTraj::minSnapTraj(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)’未定义的引用
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/planner_manager.cpp:536：对‘PolynomialTraj::one_segment_traj_gen(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, double)’未定义的引用
CMakeFiles/ego_planner_node.dir/src/planner_manager.cpp.o：在函数‘ego_planner::EGOPlannerManager::reboundReplan(Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, bool, bool)’中：
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/planner_manager.cpp:288：对‘ego_planner::PlanningVisualization::displayInitPathList(std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >, double, int)’未定义的引用
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/planner_manager.cpp:294：对‘ego_planner::PlanningVisualization::displayOptimalList(Eigen::Matrix<double, -1, -1, 0, -1, -1>, int)’未定义的引用
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/planner_manager.cpp:175：对‘PolynomialTraj::one_segment_traj_gen(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, double)’未定义的引用
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/planner_manager.cpp:105：对‘PolynomialTraj::one_segment_traj_gen(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, double)’未定义的引用
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/planner_manager.cpp:281：对‘ego_planner::PlanningVisualization::displayMultiInitPathList(std::vector<std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >, std::allocator<std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > > > >, double)’未定义的引用
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/Modules/ego_planner/ego-planner-swarm/src/planner/plan_manage/src/planner_manager.cpp:120：对‘PolynomialTraj::minSnapTraj(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)’未定义的引用
CMakeFiles/ego_planner_node.dir/src/planner_manager.cpp.o：在函数‘std::_Sp_counted_ptr<AStar*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()’中：
/usr/include/c++/7/bits/shared_ptr_base.h:376：对‘AStar::~AStar()’未定义的引用
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/libbspline_opt.so：对‘fast_planner::ObjPredictor::evaluateConstVel(int, double)’未定义的引用
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/libbspline_opt.so：对‘AStar::AstarSearch(double, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>)’未定义的引用
/home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/libbspline_opt.so：对‘AStar::getPath()’未定义的引用
collect2: error: ld returned 1 exit status
ego-planner-swarm/src/planner/plan_manage/CMakeFiles/ego_planner_node.dir/build.make:554: recipe for target '/home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/ego_planner/ego_planner_node' failed
make[2]: *** [/home/ztr/workspace/learn_mavros/amov环境/Prometheus/devel/lib/ego_planner/ego_planner_node] Error 1
CMakeFiles/Makefile2:6462: recipe for target 'ego-planner-swarm/src/planner/plan_manage/CMakeFiles/ego_planner_node.dir/all' failed
make[1]: *** [ego-planner-swarm/src/planner/plan_manage/CMakeFiles/ego_planner_node.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed

**Comment by 473867143** [comment]
删除掉build和devel，然后重新编译 ./compile_all
