### ISSUE TITLE
不能保存web_cam视频，rosrun image_view video_recorder image:=/prometheus/camera/rgb/image_raw

### ISSUE THREAD

**Issue by XXXUUUXXX** [amov-lab/Prometheus#199]
运行roslaunch prometheus_detection web_cam0.launch
rosrun image_view video_recorder image:=/prometheus/camera/rgb/image_raw
保存一个output.avi文件，但是打开报错An error occurred Could not demultiplex stream.

**Comment by XXXUUUXXX** [comment]
[ERROR] [1639625573.104258460]: Client [/image_view] wants topic /prometheus/message/web_cam to have datatype/md5sum [sensor_msgs/Image/060021388200f6f0f447d0fcd9c64743], but our version has [prometheus_msgs/Message/298ffdf82be3ca999f3a78d890347d59]. Dropping connection.

**Comment by 473867143** [comment]
你应该更新过系统，你把build和devel文件夹删掉，然后重新编译生成新的build文件夹和devel文件夹

**Comment by XXXUUUXXX** [comment]
> 

删除编译还是，不能录制视频

**Comment by 473867143** [comment]
什么报错呢？还是一样吗
