### ISSUE TITLE
执行vslam的 maplab报错：编译catkin build maplab 大量包被放弃

### ISSUE THREAD

**Issue by Chentao2000** [amov-lab/Prometheus#201]
请问 我想知道这种报错是正常的吗？
![sendpi1x0](https://user-images.githubusercontent.com/68007558/146660813-3926f5f6-7101-4bfb-811a-49fc8127e545.jpg)

**Comment by bzbsng** [comment]
蹲一个答复，我也遇到了同样的问题

**Comment by potato77** [comment]
这个功能不维护了，建议网上寻求解答。
