### ISSUE TITLE
fast-planner问题

### ISSUE THREAD

**Issue by fyx-FINR** [amov-lab/Prometheus#204]
您好，在启动了fast-planner的launch文件，飞机起飞后，在rivz中指定终点位置后会报出如图错误
![image](https://user-images.githubusercontent.com/85238681/146719783-63edc225-a692-49b6-916b-48439dba42f1.png)

`Aborted (Signal sent by tkill() 2321 1000)
[dyn_planner_node-17] process has died [pid 2321, exit code -6, cmd /home/amov/Prometheus/devel/lib/prometheus_plan_manage/dyn_planner_node /prometheus/planning/global_pcl:=/octomap_point_cloud_centers __name:=dyn_planner_node __log:=/home/amov/.ros/log/519bd35e-615a-11ec-ad88-000c296b85d7/dyn_planner_node-17.log].
log file: /home/amov/.ros/log/519bd35e-615a-11ec-ad88-000c296b85d7/dyn_planner_node-17*.log
`
请问这个该怎么解决

**Comment by potato77** [comment]
你好，fastplanner这个功能暂时不维护了，建议使用ego-planner
