### ISSUE TITLE
自主降落若干问题

### ISSUE THREAD

**Issue by XXXUUUXXX** [amov-lab/Prometheus#211]
您好
        请问，使用自己的四旋翼进行室外飞行，和仿真时候的参数相比需要更改哪些参数？px4_pos_estimator.cpp中的定位数据源，input_source设置为9时，室外飞行Z轴高度始终为0，设置为2时，高度正常，问：需要怎么修改？

**Comment by 473867143** [comment]
使用2吧，不建议使用9。因为室外的话是由GPS定位的。这里不用选择定位数据来源

**Comment by XXXUUUXXX** [comment]
谢谢您的指导
