### ISSUE TITLE
执行roslaunch prometheus_gazebo sitl.launch后出现下面的报错

### ISSUE THREAD

**Issue by wcm-123** [amov-lab/Prometheus#215]
执行上面的命令后出现三个终端
第一个终端报下面的错误
ERROR: cannot launch node of type [prometheus_control/px4_pos_estimator]: prometheus_control
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/miao/Prometheus/Modules/common/msgs
ROS path [2]=/home/miao/Prometheus/Modules/ground_station
ROS path [3]=/home/miao/Prometheus/Simulator/gazebo_simulator
ROS path [4]=/opt/ros/melodic/share
ROS path [5]=/home/miao/prometheus_px4
ROS path [6]=/home/miao/prometheus_px4/Tools/sitl_gazebo
ERROR: cannot launch node of type [prometheus_control/px4_sender]: prometheus_control
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/miao/Prometheus/Modules/common/msgs
ROS path [2]=/home/miao/Prometheus/Modules/ground_station
ROS path [3]=/home/miao/Prometheus/Simulator/gazebo_simulator
ROS path [4]=/opt/ros/melodic/share
ROS path [5]=/home/miao/prometheus_px4
ROS path [6]=/home/miao/prometheus_px4/Tools/sitl_gazebo

第三个终端什么也没有

**Comment by 473867143** [comment]
没有找到prometheus_control的功能包，重新编译一下./compile_control.sh试试呢

**Comment by wcm-123** [comment]
> 没有找到prometheus_control的功能包，重新编译一下./compile_control.sh试试呢

**Comment by wcm-123** [comment]
> > 没有找到prometheus_control的功能包，重新编译一下./compile_control.sh试试呢

./compile_control.sh执行完没有报错，当我执行./compile_planning.sh却报错

`[ 92%] Linking CXX executable /home/miao/Prometheus/devel/lib/prometheus_plan_manage/dyn_planner_node
[ 94%] Built target test_planning_static
CMakeFiles/traj_server.dir/src/traj_server.cpp.o：在函数‘cmdCallback(ros::TimerEvent const&)’中：
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/traj_server.cpp:189：对‘dyn_planner::NonUniformBspline::evaluateDeBoor(double)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/traj_server.cpp:190：对‘dyn_planner::NonUniformBspline::evaluateDeBoor(double)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/traj_server.cpp:191：对‘dyn_planner::NonUniformBspline::evaluateDeBoor(double)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/traj_server.cpp:195：对‘dyn_planner::NonUniformBspline::evaluateDeBoor(double)’未定义的引用
CMakeFiles/traj_server.dir/src/traj_server.cpp.o：在函数‘bsplineCallback(boost::shared_ptr<prometheus_plan_manage::Bspline_<std::allocator<void> > const>)’中：
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/traj_server.cpp:126：对‘dyn_planner::NonUniformBspline::NonUniformBspline(Eigen::Matrix<double, -1, -1, 0, -1, -1>, int, double, bool)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/traj_server.cpp:127：对‘dyn_planner::NonUniformBspline::setKnot(Eigen::Matrix<double, -1, 1, 0, -1, 1>)’未定义的引用
CMakeFiles/traj_server.dir/src/traj_server.cpp.o：在函数‘bsplineCallback(boost::shared_ptr<prometheus_plan_manage::Bspline_<std::allocator<void> > const>)’中：
/usr/include/c++/7/bits/stl_construct.h:98：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
CMakeFiles/traj_server.dir/src/traj_server.cpp.o：在函数‘bsplineCallback(boost::shared_ptr<prometheus_plan_manage::Bspline_<std::allocator<void> > const>)’中：
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/traj_server.cpp:134：对‘dyn_planner::NonUniformBspline::getDerivative()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/traj_server.cpp:134：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/traj_server.cpp:135：对‘dyn_planner::NonUniformBspline::getDerivative()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/traj_server.cpp:135：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/traj_server.cpp:137：对‘dyn_planner::NonUniformBspline::getTimeSpan(double&, double&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/traj_server.cpp:126：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/traj_server.cpp:135：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/traj_server.cpp:126：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
CMakeFiles/traj_server.dir/src/traj_server.cpp.o：在函数‘std::vector<dyn_planner::NonUniformBspline, std::allocator<dyn_planner::NonUniformBspline> >::~vector()’中：
/usr/include/c++/7/bits/stl_construct.h:98：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
CMakeFiles/traj_server.dir/src/traj_server.cpp.o：在函数‘dyn_planner::NonUniformBspline* std::__uninitialized_copy<false>::__uninit_copy<dyn_planner::NonUniformBspline const*, dyn_planner::NonUniformBspline*>(dyn_planner::NonUniformBspline const*, dyn_planner::NonUniformBspline const*, dyn_planner::NonUniformBspline*)’中：
/usr/include/c++/7/bits/stl_construct.h:98：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
CMakeFiles/traj_server.dir/src/traj_server.cpp.o:/usr/include/c++/7/bits/stl_construct.h:98: 跟着更多未定义的参考到 dyn_planner::NonUniformBspline::~NonUniformBspline()
collect2: error: ld returned 1 exit status
FastPlanner/plan_manage/CMakeFiles/traj_server.dir/build.make:400: recipe for target '/home/miao/Prometheus/devel/lib/prometheus_plan_manage/traj_server' failed
make[2]: *** [/home/miao/Prometheus/devel/lib/prometheus_plan_manage/traj_server] Error 1
CMakeFiles/Makefile2:5804: recipe for target 'FastPlanner/plan_manage/CMakeFiles/traj_server.dir/all' failed
make[1]: *** [FastPlanner/plan_manage/CMakeFiles/traj_server.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
CMakeFiles/dyn_planner_node.dir/src/planning_fsm.cpp.o：在函数‘dyn_planner::PlanningFSM::safetyCallback(ros::TimerEvent const&)’中：
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:375：对‘dyn_planner::EDTEnvironment::evaluateCoarseEDT(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, double const&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:386：对‘dyn_planner::EDTEnvironment::evaluateCoarseEDT(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, double const&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:415：对‘dyn_planner::EDTEnvironment::evaluateCoarseEDT(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, double const&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:375：对‘dyn_planner::EDTEnvironment::evaluateCoarseEDT(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, double const&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:415：对‘dyn_planner::EDTEnvironment::evaluateCoarseEDT(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, double const&)’未定义的引用
CMakeFiles/dyn_planner_node.dir/src/planning_fsm.cpp.o：在函数‘dyn_planner::PlanningFSM::planSearchOpt()’中：
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:514：对‘dyn_planner::NonUniformBspline::getKnot()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:523：对‘dyn_planner::KinodynamicAstar::getKinoTraj(double)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:527：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:527：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
CMakeFiles/dyn_planner_node.dir/src/planning_fsm.cpp.o：在函数‘dyn_planner::PlanningFSM::execFSMCallback(ros::TimerEvent const&)’中：
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:295：对‘dyn_planner::NonUniformBspline::evaluateDeBoor(double)’未定义的引用
CMakeFiles/dyn_planner_node.dir/src/planning_fsm.cpp.o：在函数‘dyn_planner::PlanningFSM::init(ros::NodeHandle&)’中：
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:12：对‘dyn_planner::NonUniformBspline::limit_vel_’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:13：对‘dyn_planner::NonUniformBspline::limit_acc_’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:14：对‘dyn_planner::NonUniformBspline::limit_ratio_’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:43：对‘dyn_planner::SDFMap::init(ros::NodeHandle&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:46：对‘dyn_planner::EDTEnvironment::setMap(std::shared_ptr<dyn_planner::SDFMap>)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:49：对‘dyn_planner::SDFMap_Global::init(ros::NodeHandle&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:52：对‘dyn_planner::EDTEnvironment::setMap(std::shared_ptr<dyn_planner::SDFMap_Global>)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:66：对‘dyn_planner::KinodynamicAstar::setParam(ros::NodeHandle&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:67：对‘dyn_planner::KinodynamicAstar::setEnvironment(std::shared_ptr<dyn_planner::EDTEnvironment> const&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:68：对‘dyn_planner::KinodynamicAstar::init()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:74：对‘dyn_planner::BsplineOptimizer::setParam(ros::NodeHandle&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:75：对‘dyn_planner::BsplineOptimizer::setEnvironment(std::shared_ptr<dyn_planner::EDTEnvironment> const&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/planning_fsm.cpp:46：对‘dyn_planner::EDTEnvironment::setMap(std::shared_ptr<dyn_planner::SDFMap>)’未定义的引用
CMakeFiles/dyn_planner_node.dir/src/planning_fsm.cpp.o：在函数‘dyn_planner::PlanningFSM::init(ros::NodeHandle&)’中：
/usr/include/c++/7/bits/shared_ptr_base.h:588：对‘dyn_planner::KinodynamicAstar::~KinodynamicAstar()’未定义的引用
CMakeFiles/dyn_planner_node.dir/src/planning_fsm.cpp.o：在函数‘std::_Sp_counted_ptr<dyn_planner::KinodynamicAstar*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()’中：
/usr/include/c++/7/bits/shared_ptr_base.h:376：对‘dyn_planner::KinodynamicAstar::~KinodynamicAstar()’未定义的引用
CMakeFiles/dyn_planner_node.dir/src/dyn_planner_manager.cpp.o：在函数‘dyn_planner::DynPlannerManager::~DynPlannerManager()’中：
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:6：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:6：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:6：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:6：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
CMakeFiles/dyn_planner_node.dir/src/dyn_planner_manager.cpp.o：在函数‘dyn_planner::DynPlannerManager::checkTrajCollision()’中：
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:45：对‘dyn_planner::EDTEnvironment::evaluateCoarseEDT(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, double const&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:44：对‘dyn_planner::NonUniformBspline::evaluateDeBoor(double)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:45：对‘dyn_planner::EDTEnvironment::evaluateCoarseEDT(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, double const&)’未定义的引用
CMakeFiles/dyn_planner_node.dir/src/dyn_planner_manager.cpp.o：在函数‘dyn_planner::DynPlannerManager::retrieveTrajectory()’中：
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:60：对‘dyn_planner::NonUniformBspline::getDerivative()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:60：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:61：对‘dyn_planner::NonUniformBspline::getDerivative()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:61：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:63：对‘dyn_planner::NonUniformBspline::getTimeSpan(double&, double&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:64：对‘dyn_planner::NonUniformBspline::evaluateDeBoor(double)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:61：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
CMakeFiles/dyn_planner_node.dir/src/dyn_planner_manager.cpp.o：在函数‘dyn_planner::DynPlannerManager::generateTrajectory(Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>)’中：
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:108：对‘dyn_planner::KinodynamicAstar::reset()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:111：对‘dyn_planner::KinodynamicAstar::search(Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, bool, bool, double)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:154：对‘dyn_planner::KinodynamicAstar::getSamples(double&, int&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:118：对‘dyn_planner::KinodynamicAstar::reset()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:119：对‘dyn_planner::KinodynamicAstar::search(Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, bool, bool, double)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:165：对‘dyn_planner::NonUniformBspline::getControlPointEqu3(Eigen::Matrix<double, -1, -1, 0, -1, -1>, double, Eigen::Matrix<double, -1, -1, 0, -1, -1>&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:169：对‘dyn_planner::NonUniformBspline::NonUniformBspline(Eigen::Matrix<double, -1, -1, 0, -1, -1>, int, double, bool)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:178：对‘dyn_planner::BsplineOptimizer::setControlPoints(Eigen::Matrix<double, -1, -1, 0, -1, -1>)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:180：对‘dyn_planner::BsplineOptimizer::setBSplineInterval(double)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:184：对‘dyn_planner::BsplineOptimizer::optimize(int, bool, double)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:190：对‘dyn_planner::BsplineOptimizer::getControlPoints()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:200：对‘dyn_planner::NonUniformBspline::NonUniformBspline(Eigen::Matrix<double, -1, -1, 0, -1, -1>, int, double, bool)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:203：对‘dyn_planner::NonUniformBspline::getTimeSpan(double&, double&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:206：对‘dyn_planner::NonUniformBspline::checkFeasibility(bool)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:213：对‘dyn_planner::NonUniformBspline::reallocateTime(bool)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:220：对‘dyn_planner::NonUniformBspline::getTimeSpan(double&, double&)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:227：对‘dyn_planner::NonUniformBspline::checkFeasibility(bool)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:200：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:169：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:188：对‘dyn_planner::BsplineOptimizer::optimize(int, bool, double)’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:169：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
/home/miao/Prometheus/Modules/planning/FastPlanner/plan_manage/src/dyn_planner_manager.cpp:200：对‘dyn_planner::NonUniformBspline::~NonUniformBspline()’未定义的引用
collect2: error: ld returned 1 exit status
FastPlanner/plan_manage/CMakeFiles/dyn_planner_node.dir/build.make:478: recipe for target '/home/miao/Prometheus/devel/lib/prometheus_plan_manage/dyn_planner_node' failed
make[2]: *** [/home/miao/Prometheus/devel/lib/prometheus_plan_manage/dyn_planner_node] Error 1
CMakeFiles/Makefile2:6021: recipe for target 'FastPlanner/plan_manage/CMakeFiles/dyn_planner_node.dir/all' failed
make[1]: *** [FastPlanner/plan_manage/CMakeFiles/dyn_planner_node.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j16 -l16" failed
`
