### ISSUE TITLE
./compile_all.sh编译错误

### ISSUE THREAD

**Issue by Zxr1230** [amov-lab/Prometheus#216]
在./compile_all.sh编译过程中有如下几个错误，不知道是否有影响，有影响的话该如何解决？谢谢！
错误1：
![image](https://user-images.githubusercontent.com/47097582/149534444-c942df53-8de3-47de-86be-f11562993870.png)
错误2：
![image](https://user-images.githubusercontent.com/47097582/149534532-c31d9e3a-d4ce-4a4a-af50-5de393af17c7.png)
错误3：
![image](https://user-images.githubusercontent.com/47097582/149534610-2a7c761f-22d3-4ac0-96dd-ec4d30120be5.png)
错误4：
![image](https://user-images.githubusercontent.com/47097582/149534696-0a94fa99-dc9d-4ca5-ac84-9eef8de3ec61.png)

**Comment by 473867143** [comment]
感觉不影响，有终端编译终止吗？

**Comment by Zxr1230** [comment]
> 

谢谢，没有终止，继续往下跑了，这是不是意味着没有影响？

**Comment by Zxr1230** [comment]
> 感觉不影响，有终端编译终止吗？

谢谢，没有终止，继续往下跑了，这是不是意味着没有影响？

**Comment by 473867143** [comment]
是的
