### ISSUE TITLE
Mavros功能包安装

### ISSUE THREAD

**Issue by zhaoguoming** [amov-lab/Prometheus#217]
执行下面这一步骤：
sudo ./install_geographiclib_datasets.sh
一直是下面的状态：
Installing GeographicLib geoids egm96-5
感觉下载不下来，我开了VPN，是不是我的VPN不好用？

**Comment by 473867143** [comment]
应该是VPN有问题。这个问题百度有很多这样的解决方法
https://blog.csdn.net/weixin_41865104/article/details/119418901

**Comment by zhaoguoming** [comment]
> 应该是VPN有问题。这个问题百度有很多这样的解决方法 https://blog.csdn.net/weixin_41865104/article/details/119418901

感谢大佬，我试试
