### ISSUE TITLE
 BUG: MAKE PX4_SITL GAZEBO (error: ‘TRUE’ was not declared in this scope. #define HAS_GYRO TRUE)

### ISSUE THREAD

**Issue by HITLB17** [amov-lab/Prometheus#50]
you can open the file "Firmware_v110/Tools/sitl_gazebo/include/gazebo_opticalflow_plugin.h" and change the "TRUE"  to "true";
then "make px4_sitl gazebo".
this bug only appears in version 1.10.0....... in version 1.10.1, this problem has been fixed.

**Comment by 473867143** [comment]
THS for your reminder?
Has solved, please update that repository
