### ISSUE TITLE
圆形穿越

### ISSUE THREAD

**Issue by Fakesr** [amov-lab/Prometheus#57]
怎样将检测结果可视化，还有就是在仿真时无人机无法穿越过去，会停在框内。

**Comment by potato77** [comment]
可视化需要改一下程序，将画面显示出来，这个语句之前被我们屏蔽了。
无法穿越过去这个情况没遇到过，阅读下circle_crossing.cpp，可以适当修改下策略。

**Comment by Fakesr** [comment]
> 可视化需要改一下程序，将画面显示出来，这个语句之前被我们屏蔽了。
> 无法穿越过去这个情况没遇到过，阅读下circle_crossing.cpp，可以适当地修改下策略。

能具体说一下要改什么地方吗，我好像没在ellipse_det.cpp看到能修改可视化的地方。

**Comment by potato77** [comment]
> > 可视化需要改一下程序，将画面显示出来，这个语句之前被我们屏蔽了。
> > 无法穿越过去这个情况没遇到过，阅读下circle_crossing.cpp，可以适当地修改下策略。
> 
> 能具体说一下要改什么地方吗，我好像没在ellipse_det.cpp看到能修改可视化的地方。

二次开发相关问题，可报名Prometheus课程，会有视觉模块的老师负责解答。本issue主要讨论bug和安装问题
