### ISSUE TITLE
Prometheus项目进行Prometheus仿真功能包编译时出现如下错误

### ISSUE THREAD

**Issue by JohnWoll** [amov-lab/Prometheus#59]
按照Wiki执行到Prometheus仿真功能包编译这一步时报错，执行的命令如图一所示，报的错误如图二所示，请求如何解决，但是这一步编译不成功却不影响Gazebo的仿真测试
*图一*
![图片](https://user-images.githubusercontent.com/45308682/92219293-f470e580-eecc-11ea-9d2e-8fc6336ea9dc.png)
*图二*
![图片](https://user-images.githubusercontent.com/45308682/92219360-0b173c80-eecd-11ea-87a5-ecc617918a29.png)

**Comment by potato77** [comment]
重装下gazebo试试
