### ISSUE TITLE
PX4编译如下错误

### ISSUE THREAD

**Issue by nba2kolqw** [amov-lab/Prometheus#62]
专门的PX4无法编译 试了好几次了 还重装了一次系统 是不是有什么问题

![Screenshot from 2020-09-10 22-40-09](https://user-images.githubusercontent.com/60185292/92846956-a4a38a00-f3b6-11ea-9af8-7b90d361718e.png)

**Comment by 473867143** [comment]
make distclean 
然后make px4_sitl_default gazebo
试试能否解决？

**Comment by luckyluckydadada** [comment]
我和你的情况一样，不知道为什么，PX4的原生的Firmware没问题
