### ISSUE TITLE
planning module 编译问题

### ISSUE THREAD

**Issue by YANG-DEMIN** [amov-lab/Prometheus#63]
硬件：Ubuntu18实体机，用的阿木实验室镜像，内置了project/some那个环境，可以正常跑仿真
问题描述：按照wiki下载并编译prometheus时，planning模块编译出现问题
![Screenshot from 2020-09-13 16-55-26](https://user-images.githubusercontent.com/53554275/93014693-b61ea900-f5e5-11ea-9010-00875be7a3b6.png)
/home/ydm/Prometheus/Modules/planning/FastPlanner/plan_env/ThirdParty/arc_utilities/src/arc_utilities/base64_helpers.cpp:37:45: error: 
      implicit conversion changes signedness: 'const
      __gnu_cxx::__alloc_traits<std::allocator<char> >::value_type'
      (aka 'const char') to 'std::array::size_type' (aka 'unsigned long')
      [-Werror,-Wsign-conversion]
            const int32_t n = B64IndexTable[encoded[i]] << 18 | B64Index...
                              ~~~~~~~~~~~~~ ^~~~~~~~~~
/home/ydm/Prometheus/Modules/planning/FastPlanner/plan_env/ThirdParty/arc_utilities/src/arc_utilities/base64_helpers.cpp:37:79: error: 
      implicit conversion changes signedness: 'const
      __gnu_cxx::__alloc_traits<std::allocator<char> >::value_type'
      (aka 'const char') to 'std::array::size_type' (aka 'unsigned long')
      [-Werror,-Wsign-conversion]
  ...= B64IndexTable[encoded[i]] << 18 | B64IndexTable[encoded[i + 1]] << 12 ...

**Comment by 473867143** [comment]
@panpanyunshi  这个报错是什么原因？
