### ISSUE TITLE
Fast Planner environment 

### ISSUE THREAD

**Issue by Amit10311** [amov-lab/Prometheus#67]
Thank you for this great package for simulating MAV.  I want to set up my own environment and use a `fast planner` in the simulation.
Can you please guide me on how to set up the `fast-planner` from your package and excluding other modules?
If you could also provide the `rqt_graph` of `fastplanner` launch that would be also useful. I look forward to hearing from you. Thank you for your valuable time.

**Comment by potato77** [comment]
We have Wiki to help you. But it is Chinese. Sorry, we cant provide English wiki now.
