### ISSUE TITLE
prometheus_msgs编译功能包找不到

### ISSUE THREAD

**Issue by li-1999** [amov-lab/Prometheus#69]

**Comment by potato77** [comment]
更新下代码，然后make clean后重新编译试试

**Comment by Fllying** [comment]
我更新完代码，还是出现这个问题，请问缺少什么包没有安装嘛？百度找不到答案，咱这个应该是自定义的msgs消息

**Comment by Fllying** [comment]
@li-1999 请问下，您解决这个问题了嘛？

**Comment by 473867143** [comment]
环境变量source了吗

**Comment by Fllying** [comment]
@473867143 我用了catkin_make命令，所以出现了上述错误，后来看了wiki之后重新操作就好了，不过新的错误又出现了，百度都解决了，学习Linux就是这样，问题不断出现，慢慢解决呗！

**Comment by li-1999** [comment]
解决了&nbsp; &nbsp;感谢回复&nbsp; 抱歉最近没看邮件




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "River ***@***.***&gt;; 
发送时间: 2021年4月24日(星期六) 晚上10:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [amov-lab/Prometheus] prometheus_msgs编译功能包找不到 (#69)





 
@li-1999 请问下，您解决这个问题了嘛？
