### ISSUE TITLE
Octomap无法建图

### ISSUE THREAD

**Issue by nba2kolqw** [amov-lab/Prometheus#71]
跟着教程走的 但是octomap没有建图 rtapmap 倒是成功了 请问有没有什么解决方法呢？谢谢
![Screenshot from 2020-10-15 20-37-22](https://user-images.githubusercontent.com/60185292/96200036-f051d200-0f26-11eb-924a-973ad8994696.png)

**Comment by potato77** [comment]
提供的信息太少了，你连启动的launch都没说用的哪个？可能性很多，比如你没装octomap的包

**Comment by nba2kolqw** [comment]
跑的就是教程里的那个launch
roslaunch prometheus_gazebo sitl_octomap.launch

所有教程里的依赖项也都装了
好像问题是没有point cloud 输出 请问是不是要装个pcl什么的

**Comment by w407022008** [comment]
#93

**Comment by potato77** [comment]
> 跑的就是教程里的那个launch
> roslaunch prometheus_gazebo sitl_octomap.launch
> 
> 所有教程里的依赖项也都装了
> 好像问题是没有point cloud 输出 请问是不是要装个pcl什么的

现在还有问题吗？感觉是有依赖项没安装

**Comment by brain726** [comment]
你看一下激光雷达模型能不能输出点云，如果不能就是没装激光雷达的模型文件

**Comment by brain726** [comment]
你看一下激光雷达模型能不能输出点云，如果不能就是没装激光雷达的模型文件
