### ISSUE TITLE
KCF目标识别程序的bug

### ISSUE THREAD

**Issue by shupx** [amov-lab/Prometheus#72]
[KCF识别人并飞到所选人面前的仿真有点问题。按照object_tracking.yaml的参数，无人机应该飞到所选人物面前1.5m停下，但是仿真中给无人机的位置指令不断增大，导致无人机直接飞向人并撞向人。]
这说明无人机的导引程序有问题，即object_tracking.cpp有问题。经排查，修改object_tracking.cpp第248行代码如下即可：
`pos_des_prev[i] = drone_pos[i];`
并且修改object_tracking.yaml中的导引比例参数使得无人机速度合适：
##比例参数
`kpx_track: 3 `
`kpy_track: 3 `
`kpz_track: 3 `
修改后，无人机可以飞到选定的人面前1.5m后停下。

这个bug是因为object_tracking.cpp中根据KCF选框位置计算出的本来是无人机速度指令，但是object_tracking.cpp第242行却将速度指令经过一次积分变成了位置指令position_ref[i]，积分间隔0.05s（根据节点频率20Hz推算出）。
`242行： Command_Now.Reference_State.position_ref[i] = pos_des_prev[i] + vel_command[i]* 0.05;`
`248行：pos_des_prev[i] = Command_Now.Reference_State.position_ref[i]; `
然而仿真时很难保证节点频率就是整整20Hz，经过242行和248行的不断迭代，积分出的位置指令误差会不断累积，导致发散。
为了使得误差不累积，可以在每次积分后将本时刻的真实位置drone_pos作为下一个时刻的积分初值，而不是按照原来248行所写，把上一个时刻的指令Command_Now作为下一个时刻的积分初值。
所以把第248行改成：
`pos_des_prev[i] = drone_pos[i];`
并修改比例参数就可以啦！

**Comment by potato77** [comment]
追踪的控制逻辑，我们会重新编写，多谢
