### ISSUE TITLE
执行git submodule update --init --recursive时报错无法在子模组路径 'Tools/sitl_gazebo' 中检出 '169d48217df89922e9fae72ef34fa46ce2e209dd'，

### ISSUE THREAD

**Issue by fantasyfukystar** [amov-lab/Prometheus#82]
无法在子模组路径 'Tools/sitl_gazebo' 中检出 '169d48217df89922e9fae72ef34fa46ce2e209dd'

**Comment by fantasyfukystar** [comment]
fatal: 引用不是一个树：898d96f89973aaa6b124aa96e52e60e17947473b
fatal: 引用不是一个树：38af96421cfd88209bbe0add60bd933627672368
无法在子模组路径 'Tools/sitl_gazebo' 中检出 '898d96f89973aaa6b124aa96e52e60e17947473b'
无法在子模组路径 'src/drivers/gps/devices' 中检出 '38af96421cfd88209bbe0add60bd933627672368'

**Comment by 473867143** [comment]
你使用的是Ubuntu16.04？？？
请升级到Ubuntu18.04

**Comment by fantasyfukystar** [comment]
系统升级到ubuntu18.04可以解决上述问题，感谢楼上的解决办法

**Comment by wcm-123** [comment]
> 

我就是18.04但第一次执行这个命令就是这样的错误，不知道怎么解决
