### ISSUE TITLE
关于P300_basic的gazebo环境加载不出

### ISSUE THREAD

**Issue by lddddd1997** [amov-lab/Prometheus#84]
compile_all编译后没问题
**roslaunch prometheus_gazebo sitl.launch**出现如下错误
_[gazebo-3] process has died [pid 31530, exit code 139, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /home/jys/amov_ws/src/Prometheus/Simulator/gazebo_simulator/worlds/empty.world __name:=gazebo_
将sitl.launch文件中的P300_basic模型替换成iris模型无问题
请问该如何解决呢？

**Comment by 473867143** [comment]
建议使用18.04系统，16.04需要尝试一下，是否会复现此问题

**Comment by lddddd1997** [comment]
将px4版本改成1.10.1即可
