### ISSUE TITLE
ERR in sitl_indoor_competition.launch

### ISSUE THREAD

**Issue by w407022008** [amov-lab/Prometheus#93]
Hi there!
Nice a project! But there are some err, pls correct them.
1.  parameter name -[subscriber](https://github.com/amov-lab/Prometheus/blob/6c4656eedb4d4ec184b504fc13a8f2237b5fffca/Simulator/gazebo_simulator/launch_basic/sitl_indoor_competition.launch#L92) & [config](https://github.com/amov-lab/Prometheus/blob/6c4656eedb4d4ec184b504fc13a8f2237b5fffca/Simulator/gazebo_simulator/launch_basic/sitl_indoor_competition.launch#L93) - should be modified same as [camera_topic](https://github.com/amov-lab/Prometheus/blob/6c4656eedb4d4ec184b504fc13a8f2237b5fffca/Simulator/gazebo_simulator/launch_basic/sitl_indoor_competition.launch#L104) & [camera_info](https://github.com/amov-lab/Prometheus/blob/6c4656eedb4d4ec184b504fc13a8f2237b5fffca/Simulator/gazebo_simulator/launch_basic/sitl_indoor_competition.launch#L105).
2.  [YAML](https://github.com/amov-lab/Prometheus/blob/6c4656eedb4d4ec184b504fc13a8f2237b5fffca/Simulator/gazebo_simulator/launch_basic/sitl_indoor_competition.launch#L93) file could not probably found automatically, pls use $(find *) if needed.
3. [.sdf](https://github.com/amov-lab/Prometheus/blob/6c4656eedb4d4ec184b504fc13a8f2237b5fffca/Simulator/gazebo_simulator/launch_basic/sitl_indoor_competition.launch#L8) file missing.
Thx! :)

**Comment by potato77** [comment]
thanks!
